package: school 
version: '1.0.1'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/school

requires:
    php:
        version: '>8.3,<9'
    redaxo: ^5.18
    packages:
        plus_bs5: ">=0,<2"
        yform: "^4"
        yform_spam_protection: ">=1"
        yform_field: ">=1"
        events: ">=5,<7"
        tracks: "^4.0"

page:
    title: translate:school_title
    icon: rex-icon fa-school
    block: system
    prio: 11
    perm: school

pages:
    school/inbox:
        title: translate:school_inbox
        perm: school['inbox']
        icon: rex-icon fa-envelope-o
    school/course:
        title: translate:school_course
        perm: school['course']
        icon: rex-icon fa-users
    school/project:
        title: translate:school_project
        perm: school['project']
        icon: rex-icon fa-table
    school/room:
        title: translate:school_room
        perm: school['room']
        icon: rex-icon fa-door-open
    school/subject:
        title: translate:school_subject
        perm: school['subject']
        icon: rex-icon fa-table
    school/team:
        title: translate:school_team
        perm: school['team']
        icon: rex-icon fa-user-o
    school/team/team:
        title: translate:school_team
        perm: school['team']
        icon: rex-icon fa-user-o
    school/team/team_tags:
        title: translate:school_team_tags
        perm: school['team']
        icon: rex-icon fa-vcard-o

    school/settings:
        title: translate:school_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    school/docs:
        title: translate:school_docs
        subPath: README.md 
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: school[docs]
